-- =====================================================
-- AUTO-GENERATED PRODUCT SEED  (generated from lib/products.json)
-- Generator: scripts/generate-product-sql.js  —  DO NOT EDIT BY HAND
-- =====================================================
--
-- Prerequisites (run first, in order):
--   schema.sql, migration-001-addresses.sql, migration-002-rls-policies.sql,
--   migration-003-product-slug.sql
--
-- Idempotent: products.id is derived deterministically from the slug via
-- uuid_generate_v5(), and rows upsert ON CONFLICT (slug). Re-running this file
-- refreshes catalog fields without ever changing a product's UUID.
-- =====================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'lamps-lamp1'),
  'lamps-lamp1',
  'Rustic Charm Lamp',
  'A stunning rustic lamp that brings warmth and character to any space. Features a unique design with natural textures and earthy tones. Perfect for creating a cozy ambiance in living rooms, bedrooms, or study areas. Handcrafted with attention to detail.',
  'lamps',
  2299,
  2799,
  NULL,
  18,
  '["/images/products/lamps/lamp1/34952bf0-2a35-11f0-8ecc-91091a12b35c.jpg","/images/products/lamps/lamp1/c77cb000-3e62-11f0-8b94-d7698adcec77.jpg","/images/products/lamps/lamp1/c7845120-3e62-11f0-8b94-d7698adcec77.jpg"]'::jsonb,
  NULL,
  'new',
  false,
  4.6,
  32,
  'Clean with a soft, dry cloth. Avoid using harsh chemicals. Keep away from direct sunlight to prevent fading. Use LED bulbs for optimal performance and energy efficiency.',
  'Free shipping on orders above ₹2000. Standard delivery takes 3-5 business days. Express delivery available for metro cities.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'lamps-lamp2'),
  'lamps-lamp2',
  'Modern Elegance Lamp',
  'A beautifully crafted lamp that combines modern design with rustic charm. Perfect for adding ambient lighting to any room. Made with premium materials and attention to detail, this lamp will be a statement piece in your home decor.',
  'lamps',
  2499,
  2999,
  NULL,
  17,
  '["/images/products/lamps/lamp2/IMG_2517.jpeg","/images/products/lamps/lamp2/IMG_2585.jpeg"]'::jsonb,
  NULL,
  'trending',
  false,
  4.5,
  28,
  'Clean with a soft, dry cloth. Avoid using harsh chemicals. Keep away from direct sunlight to prevent fading. For optimal performance, use LED bulbs.',
  'Free shipping on orders above ₹2000. Standard delivery takes 3-5 business days. Express delivery available for metro cities.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'lamps-lamp3'),
  'lamps-lamp3',
  'Contemporary Style Lamp',
  'An elegant and sophisticated lamp design that brings warmth and style to your living space. Features a unique base design and premium finish. Ideal for bedside tables, study desks, or as a decorative accent piece.',
  'lamps',
  2799,
  3299,
  NULL,
  15,
  '["/images/products/lamps/lamp3/2025-11-18_19d636c83adc7.webp","/images/products/lamps/lamp3/2025-11-18_4ef0ad1cd37bd8.webp","/images/products/lamps/lamp3/2025-11-18_98ad47b29ecd68.webp","/images/products/lamps/lamp3/2025-11-18_d5a4285ca59b28.webp"]'::jsonb,
  NULL,
  'editors-choice',
  false,
  4.7,
  42,
  'Dust regularly with a microfiber cloth. Use mild soap and water for deeper cleaning. Ensure the lamp is unplugged before cleaning. Replace bulbs as needed.',
  'Free shipping on all orders. Standard delivery: 3-5 business days. Express delivery: 1-2 business days (metro cities only).',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'lamps-lamp4'),
  'lamps-lamp4',
  'Artistic Designer Lamp',
  'A stunning contemporary lamp that blends functionality with artistic design. Perfect for modern interiors, this lamp features a unique silhouette and premium materials. Creates the perfect ambiance for any setting.',
  'lamps',
  3199,
  3799,
  NULL,
  16,
  '["/images/products/lamps/lamp4/2025-06-19_055478830772c8.webp","/images/products/lamps/lamp4/2025-06-19_17e91217ec664.webp","/images/products/lamps/lamp4/2025-06-19_1f854ddc599c88.webp","/images/products/lamps/lamp4/2025-06-19_5e9df64ab4803.webp","/images/products/lamps/lamp4/dfd.png","/images/products/lamps/lamp4/IMG_8965.png","/images/products/lamps/lamp4/IMG_8987.png"]'::jsonb,
  NULL,
  NULL,
  false,
  4.6,
  35,
  'Wipe clean with a damp cloth. Avoid abrasive cleaners. Keep in a dry place. Use compatible bulbs as specified in the product manual.',
  'Free shipping on orders above ₹2500. Standard delivery: 4-6 business days. Express delivery available.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'lamps-lamp5'),
  'lamps-lamp5',
  'Minimalist Modern Lamp',
  'A sleek and minimalist lamp design that complements contemporary interiors. Features clean lines and a sophisticated aesthetic. Perfect for modern homes and offices. Provides excellent lighting while serving as a stylish decor piece.',
  'lamps',
  2899,
  3399,
  NULL,
  15,
  '["/images/products/lamps/lamp5/09d2f170-e355-11f0-a875-5de986fdb37b.jpg","/images/products/lamps/lamp5/1e1873a1-f9d3-11f0-8107-5181291209f7.jpg","/images/products/lamps/lamp5/ea475e10-d524-11f0-b9e0-49223024dc0c.jpg","/images/products/lamps/lamp5/ea486f80-d524-11f0-b9e0-49223024dc0c.jpg"]'::jsonb,
  NULL,
  'trending',
  false,
  4.8,
  48,
  'Clean with a soft microfiber cloth. Avoid water contact with electrical components. Use recommended wattage bulbs. Keep away from heat sources.',
  'Free shipping on orders above ₹2500. Standard delivery: 3-5 business days. Express delivery available for select cities.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'lamps-glow-arc'),
  'lamps-glow-arc',
  'Glow Arc Pendant Lamp',
  'An arc-shaped pendant lamp with a smooth matte finish, designed to hang over dining tables or reading nooks. The curved silhouette creates a soft halo effect that''s as beautiful unlit as it is glowing.',
  'lamps',
  1999,
  2499,
  NULL,
  20,
  '["/images/products/lamps/lamp2/IMG_2517.jpeg","/images/products/lamps/lamp2/IMG_2585.jpeg"]'::jsonb,
  NULL,
  'sale',
  false,
  4.4,
  19,
  'Wipe with a dry microfiber cloth. Do not use wet cloths near the cord or bulb fitting. Hang on a sturdy hook rated for 500g.',
  'Free shipping on orders above ₹2000. Standard delivery: 3-5 business days.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'lamps-terra-glow'),
  'lamps-terra-glow',
  'Terra Glow Table Lamp',
  'Earth-toned 3D-printed lamp with a terracotta-inspired palette. The geometric lattice pattern casts stunning shadow patterns on your walls. A conversation-starter for any boho or earthy interior.',
  'lamps',
  2149,
  2599,
  NULL,
  17,
  '["/images/products/lamps/lamp1/34952bf0-2a35-11f0-8ecc-91091a12b35c.jpg","/images/products/lamps/lamp1/c77cb000-3e62-11f0-8b94-d7698adcec77.jpg","/images/products/lamps/lamp1/c7845120-3e62-11f0-8b94-d7698adcec77.jpg"]'::jsonb,
  NULL,
  'sale',
  false,
  4.5,
  23,
  'Dust gently with a dry cloth. Avoid placing near high-humidity areas. Use bulbs under 15W for best shadow effects.',
  'Free shipping on orders above ₹2000. Standard delivery: 3-5 business days.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'lamps-lunar-night'),
  'lamps-lunar-night',
  'Lunar Night Lamp',
  'Inspired by the moon''s craters and surface, this night lamp casts a warm celestial glow. Ideal as a bedside lamp, nursery light, or a thoughtful gift. Printed in translucent filament for maximum diffusion.',
  'lamps',
  1699,
  1999,
  NULL,
  15,
  '["/images/products/lamps/lamp3/2025-11-18_98ad47b29ecd68.webp","/images/products/lamps/lamp3/2025-11-18_d5a4285ca59b28.webp","/images/products/lamps/lamp3/2025-11-18_19d636c83adc7.webp"]'::jsonb,
  NULL,
  'trending',
  false,
  4.9,
  67,
  'Clean with a soft dry cloth only. Protect from drops. Use a 5W LED bulb for optimal moon-like effect.',
  'Free shipping on all orders. Standard delivery: 3-5 business days.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'organizers-organizer1'),
  'organizers-organizer1',
  'Multi-Purpose Desk Organizer',
  'A beautifully designed organizer that helps you keep your space tidy and organized. Features multiple compartments and a sleek design that complements any decor style. Perfect for desks, shelves, or countertops.',
  'organizers',
  1899,
  2299,
  NULL,
  17,
  '["/images/products/organizers/organizer1/2025-02-05_2c663f44c88c1.webp","/images/products/organizers/organizer1/2025-02-20_225ce91d4d28.webp"]'::jsonb,
  NULL,
  NULL,
  false,
  4.4,
  31,
  'Clean with a soft cloth and mild detergent. Avoid soaking in water. Dry thoroughly after cleaning. Store in a cool, dry place.',
  'Free shipping on orders above ₹1500. Standard delivery: 3-5 business days. Express delivery available for select cities.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'organizers-organizer2'),
  'organizers-organizer2',
  'Premium Storage Organizer',
  'An elegant storage solution that combines form and function. This organizer features a modern design with ample storage space. Ideal for organizing office supplies, cosmetics, or small accessories.',
  'organizers',
  2199,
  2599,
  NULL,
  15,
  '["/images/products/organizers/organizer2/d6452f90-c897-11ef-b2c7-2dc1a7392ad7.png","/images/products/organizers/organizer2/d64d9400-c897-11ef-b2c7-2dc1a7392ad7.png","/images/products/organizers/organizer2/d657cd30-c897-11ef-b2c7-2dc1a7392ad7.jpg","/images/products/organizers/organizer2/d65a6540-c897-11ef-b2c7-2dc1a7392ad7.jpg"]'::jsonb,
  NULL,
  NULL,
  false,
  4.3,
  24,
  'Wipe clean with a damp cloth. Use mild soap for stubborn stains. Avoid using harsh chemicals. Keep away from direct heat sources.',
  'Free shipping on orders above ₹2000. Standard delivery: 4-6 business days. Express delivery available.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'organizers-organizer3'),
  'organizers-organizer3',
  'TISTWO Tissue Box Organizer',
  'A stylish tissue box organizer with hidden magnets for secure placement. Features a modern design that blends seamlessly with any decor. Keeps tissues easily accessible while maintaining a clean, organized look.',
  'organizers',
  1599,
  1899,
  NULL,
  16,
  '["/images/products/organizers/organizer3/TISTWO20tissue20box.jpg","/images/products/organizers/organizer3/TISTWO20tissue20box202.jpg","/images/products/organizers/organizer3/Hidden20magnets (2).jpg"]'::jsonb,
  NULL,
  'new',
  false,
  4.5,
  27,
  'Clean with a damp cloth. Avoid excessive moisture. Magnets are strong - handle with care. Suitable for standard tissue box sizes.',
  'Free shipping on orders above ₹1500. Standard delivery: 3-5 business days. Lightweight and easy to install.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'organizers-organizer4'),
  'organizers-organizer4',
  'THALOR Kitchen Tissue Holder',
  'A practical kitchen tissue holder designed for convenience and style. Features easy mounting and quick tissue access. Perfect for kitchens, dining areas, or bathrooms. Durable construction ensures long-lasting use.',
  'organizers',
  1399,
  1699,
  NULL,
  18,
  '["/images/products/organizers/organizer4/THALOR20kitchen20tissue20holder.jpg","/images/products/organizers/organizer4/THALOR20kitchen20tissue20holder202.jpg","/images/products/organizers/organizer4/THALOR20kitchen20tissue20holder203.jpg"]'::jsonb,
  NULL,
  NULL,
  false,
  4.6,
  39,
  'Wipe clean with a damp cloth. Avoid harsh chemicals. Easy to install and remove. Compatible with standard paper towel rolls.',
  'Free shipping on orders above ₹1200. Standard delivery: 3-5 business days. Includes mounting hardware.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'organizers-stackdesk-pro'),
  'organizers-stackdesk-pro',
  'StackDesk Pro Organizer',
  'A modular stacking desk organizer system with interlocking tiers. Configure it as a pen caddy, cable manager, or card holder — all in one elegant unit. Printed in smooth matte PLA for a professional look.',
  'organizers',
  999,
  1299,
  NULL,
  23,
  '["/images/products/organizers/organizer1/2025-02-05_2c663f44c88c1.webp","/images/products/organizers/organizer1/2025-02-20_225ce91d4d28.webp"]'::jsonb,
  NULL,
  'sale',
  false,
  4.5,
  22,
  'Wipe with a dry or slightly damp cloth. Do not immerse in water. Avoid placing near radiators.',
  'Free shipping on orders above ₹1200. Standard delivery: 3-5 business days.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'organizers-cable-den'),
  'organizers-cable-den',
  'Cable Den Desk Tidy',
  'Tame the cable chaos on your desk with this wall-mountable or freestanding cable organizer. Hidden routing channels keep USB, power, and headphone cables neat and tangle-free. Minimal design suits any workspace.',
  'organizers',
  799,
  999,
  NULL,
  20,
  '["/images/products/organizers/organizer2/d657cd30-c897-11ef-b2c7-2dc1a7392ad7.jpg","/images/products/organizers/organizer2/d6452f90-c897-11ef-b2c7-2dc1a7392ad7.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.3,
  18,
  'Wipe clean. Do not apply pressure to cable slots. Compatible with cables up to 6mm diameter.',
  'Free shipping on orders above ₹1200. Standard delivery: 3-5 business days.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'organizers-mag-tissue'),
  'organizers-mag-tissue',
  'MagBase Tissue Caddy',
  'Magnetic-base tissue caddy that stays put on metallic surfaces — fridges, filing cabinets, whiteboards. A clean alternative to plastic holders, printed in a range of matte finishes. Gift-ready packaging included.',
  'organizers',
  1299,
  1599,
  NULL,
  19,
  '["/images/products/organizers/organizer3/TISTWO20tissue20box.jpg","/images/products/organizers/organizer3/Hidden20magnets (2).jpg"]'::jsonb,
  NULL,
  'trending',
  false,
  4.7,
  33,
  'Wipe with a damp cloth. Magnets are strong — keep away from credit cards. Fits standard 200-pull tissue boxes.',
  'Free shipping on orders above ₹1200. Standard delivery: 3-5 business days.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'organizers-counter-caddy'),
  'organizers-counter-caddy',
  'Counter Caddy Kitchen Holder',
  'Keep your kitchen counter clutter-free with this slim and practical caddy. Holds paper towels, spatulas, and small utensils in one spot. Weighted base prevents tipping. Dishwasher safe.',
  'organizers',
  1199,
  1499,
  NULL,
  20,
  '["/images/products/organizers/organizer4/THALOR20kitchen20tissue20holder.jpg","/images/products/organizers/organizer4/THALOR20kitchen20tissue20holder202.jpg"]'::jsonb,
  NULL,
  'new',
  false,
  4.4,
  29,
  'Dishwasher safe on the top rack. Avoid high temperatures. Check stability before placing heavy items.',
  'Free shipping on orders above ₹1200. Standard delivery: 3-5 business days.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'planters-planter1'),
  'planters-planter1',
  'CACTIA Cactus Planter',
  'A charming cactus-themed planter perfect for succulents and small plants. Features a unique design that adds personality to any space. Made with durable materials and excellent drainage. Ideal for indoor gardening enthusiasts.',
  'planters',
  1499,
  1799,
  NULL,
  17,
  '["/images/products/planters/planter1/CACTIA20planter202.jpg","/images/products/planters/planter1/CACTIA20planter203.jpg"]'::jsonb,
  NULL,
  'trending',
  false,
  4.7,
  44,
  'Clean regularly to prevent buildup. Ensure proper drainage. Use a saucer to protect surfaces. Perfect for cacti and succulents. Suitable for indoor use.',
  'Free shipping on orders above ₹1200. Standard delivery: 3-5 business days. Handle with care during unpacking.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'planters-planter2'),
  'planters-planter2',
  'STEMRA Stackable Planter Set',
  'Innovative stackable planters that maximize vertical space. Perfect for creating a living wall or herb garden. Features modular design for flexible arrangements. Ideal for small spaces and urban gardening.',
  'planters',
  2199,
  2699,
  NULL,
  19,
  '["/images/products/planters/planter2/STACKABLE.jpg","/images/products/planters/planter2/STACKABLE20(2).jpg","/images/products/planters/planter2/STEMRA2011.jpg","/images/products/planters/planter2/STEMRA2012.jpg"]'::jsonb,
  NULL,
  'editors-choice',
  false,
  4.8,
  51,
  'Clean with mild soap and water. Ensure proper drainage in each tier. Stack securely on a stable surface. Suitable for herbs, flowers, and small plants.',
  'Free shipping on orders above ₹2000. Standard delivery: 4-6 business days. Includes stacking hardware.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'planters-planter3'),
  'planters-planter3',
  'Artisan Geometric Planter',
  'A beautiful geometric planter that brings nature into your home. Crafted with care, this planter is perfect for indoor plants and adds a touch of greenery to any space. Features excellent drainage and a timeless faceted design. NOTE: original .heic images pending conversion — currently showing alternate display images.',
  'planters',
  1599,
  1999,
  NULL,
  20,
  '["/images/products/planters/planter1/CACTIA20planter202.jpg","/images/products/planters/planter1/CACTIA20planter203.jpg"]'::jsonb,
  NULL,
  NULL,
  false,
  4.8,
  56,
  'Clean regularly to prevent buildup. Ensure proper drainage. Use a saucer to protect surfaces. Avoid overwatering. Suitable for both indoor and outdoor use.',
  'Free shipping on all orders. Standard delivery: 3-5 business days. Handle with care during unpacking.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'planters-herb-tower'),
  'planters-herb-tower',
  'Herb Tower Planter',
  'A tall tower planter with three self-watering pockets — perfect for growing basil, mint, and coriander on your kitchen windowsill. The modular tiers can be removed for easy harvesting. Compact and lightweight.',
  'planters',
  1299,
  1599,
  NULL,
  19,
  '["/images/products/planters/planter2/STEMRA2011.jpg","/images/products/planters/planter2/STEMRA2012.jpg","/images/products/planters/planter2/STACKABLE.jpg"]'::jsonb,
  NULL,
  'sale',
  false,
  4.6,
  38,
  'Rinse with water to clean. Ensure bottom drainage hole is clear. Not suitable for outdoor use in heavy rain. Best for herbs and trailing plants.',
  'Free shipping on orders above ₹1200. Standard delivery: 3-5 business days.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'planters-wall-bloom'),
  'planters-wall-bloom',
  'Wall Bloom Hanging Planter',
  'Mount it, hang it, or set it on a shelf — this versatile planter works three ways. The integrated hanger is load-tested for 1.5kg. Comes in warm terracotta-inspired tones that look gorgeous with trailing pothos or string-of-pearls.',
  'planters',
  899,
  1099,
  NULL,
  18,
  '["/images/products/planters/planter1/CACTIA20planter202.jpg","/images/products/planters/planter1/CACTIA20planter203.jpg"]'::jsonb,
  NULL,
  'sale',
  false,
  4.5,
  29,
  'Wipe clean. Ensure wall anchor is secure before hanging. Not suitable for plants heavier than 1.5kg.',
  'Free shipping on orders above ₹1000. Standard delivery: 3-5 business days. Wall anchors included.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'planters-urban-pot'),
  'planters-urban-pot',
  'Urban Pocket Pot Set',
  'A set of two minimalist pocket pots for desk succulents or air plants. The slim silhouette takes up barely any desk real estate, while the built-in drainage keeps your plants happy. A great gifting option.',
  'planters',
  699,
  899,
  NULL,
  22,
  '["/images/products/planters/planter2/STACKABLE20(2).jpg","/images/products/planters/planter2/STACKABLE.jpg"]'::jsonb,
  NULL,
  'new',
  false,
  4.4,
  21,
  'Rinse with clean water. Suitable for succulents and air plants only. Avoid direct outdoor sun for extended periods.',
  'Free shipping on orders above ₹800. Standard delivery: 3-5 business days. Set of 2 pots.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'planters-terrace-trio'),
  'planters-terrace-trio',
  'Terrace Trio Planter Bundle',
  'Three graduating-size planters sold as a bundle — small for succulents, medium for herbs, large for a statement monstera. Designed to stack or display in a row. A popular housewarming gift.',
  'planters',
  2499,
  2999,
  NULL,
  17,
  '["/images/products/planters/planter2/STEMRA2011.jpg","/images/products/planters/planter2/STEMRA2012.jpg","/images/products/planters/planter2/STACKABLE.jpg","/images/products/planters/planter2/STACKABLE20(2).jpg"]'::jsonb,
  NULL,
  'trending',
  false,
  4.9,
  72,
  'Clean with mild soap and water. Ensure drainage holes are clear. Bundle includes three matching saucers.',
  'Free shipping on all orders above ₹2000. Standard delivery: 4-6 business days. Bundle packed securely.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'planters-geo-fern'),
  'planters-geo-fern',
  'Geo Fern Floor Planter',
  'A bold geometric floor planter that makes a statement in hallways, living corners, and entryways. Its 30cm height is ideal for ferns, fiddle-leaf figs, or tall ornamental grasses. Printed in weather-resistant PETG.',
  'planters',
  3499,
  3999,
  NULL,
  13,
  '["/images/products/planters/planter1/CACTIA20planter202.jpg","/images/products/planters/planter1/CACTIA20planter203.jpg"]'::jsonb,
  NULL,
  'editors-choice',
  false,
  4.7,
  41,
  'Wipe clean with a damp cloth. Suitable for indoor and covered outdoor use. Use a saucer to protect flooring. Supports up to 3kg of soil.',
  'Free shipping on all orders. Standard delivery: 5-7 business days. Packed in reinforced box.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'pooja-decor-ganesha'),
  'pooja-decor-ganesha',
  'Golden Ganesha Idol',
  'Golden Ganesha Idol — intricately detailed and beautifully 3D printed for your sacred space. Made to order in vivid, long-lasting multi-colour.',
  'pooja-decor',
  899,
  1199,
  NULL,
  25,
  '["/images/3dps/products/key-07.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.9,
  78,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'pooja-decor-trishul'),
  'pooja-decor-trishul',
  'Shiva Trishul & Om Stand',
  'Shiva Trishul & Om Stand — intricately detailed and beautifully 3D printed for your sacred space. Made to order in vivid, long-lasting multi-colour.',
  'pooja-decor',
  699,
  999,
  NULL,
  30,
  '["/images/3dps/products/key-08.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.8,
  54,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'pooja-decor-incense'),
  'pooja-decor-incense',
  'Lotus Incense Holder',
  'Lotus Incense Holder — intricately detailed and beautifully 3D printed for your sacred space. Made to order in vivid, long-lasting multi-colour.',
  'pooja-decor',
  299,
  449,
  NULL,
  33,
  '["/images/3dps/products/key-11.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.7,
  41,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'pooja-decor-saraswati'),
  'pooja-decor-saraswati',
  'Maa Saraswati Idol',
  'Maa Saraswati Idol — intricately detailed and beautifully 3D printed for your sacred space. Made to order in vivid, long-lasting multi-colour.',
  'pooja-decor',
  999,
  1399,
  NULL,
  29,
  '["/images/3dps/products/key-12.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.8,
  33,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'pooja-decor-shiva'),
  'pooja-decor-shiva',
  'Meditating Mahadev Idol',
  'Meditating Mahadev Idol — intricately detailed and beautifully 3D printed for your sacred space. Made to order in vivid, long-lasting multi-colour.',
  'pooja-decor',
  1199,
  1599,
  NULL,
  25,
  '["/images/3dps/products/pooja-01.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.9,
  62,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'pooja-decor-lakshmi'),
  'pooja-decor-lakshmi',
  'Mahalakshmi Idol on Lotus',
  'Mahalakshmi Idol on Lotus — intricately detailed and beautifully 3D printed for your sacred space. Made to order in vivid, long-lasting multi-colour.',
  'pooja-decor',
  1099,
  1499,
  NULL,
  27,
  '["/images/3dps/products/pooja-02.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.8,
  47,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'pooja-decor-krishna'),
  'pooja-decor-krishna',
  'Bal Krishna Idol',
  'Bal Krishna Idol — intricately detailed and beautifully 3D printed for your sacred space. Made to order in vivid, long-lasting multi-colour.',
  'pooja-decor',
  799,
  1099,
  NULL,
  27,
  '["/images/3dps/products/pooja-03.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.7,
  39,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'pooja-decor-temple'),
  'pooja-decor-temple',
  'Kedarnath Temple Miniature',
  'Kedarnath Temple Miniature — intricately detailed and beautifully 3D printed for your sacred space. Made to order in vivid, long-lasting multi-colour.',
  'pooja-decor',
  1499,
  1999,
  NULL,
  25,
  '["/images/3dps/products/pooja-04.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.9,
  58,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'pooja-decor-sign'),
  'pooja-decor-sign',
  'Shrikrishna Devotional Sign',
  'Shrikrishna Devotional Sign — intricately detailed and beautifully 3D printed for your sacred space. Made to order in vivid, long-lasting multi-colour.',
  'pooja-decor',
  499,
  699,
  NULL,
  29,
  '["/images/3dps/products/key-06.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.6,
  27,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-piano'),
  'keyrings-piano',
  'Piano Keys Keychain',
  'Piano Keys Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  149,
  249,
  NULL,
  40,
  '["/images/3dps/products/key-01.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.7,
  44,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-popit'),
  'keyrings-popit',
  'Pop-It Fidget Keychain',
  'Pop-It Fidget Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  129,
  199,
  NULL,
  35,
  '["/images/3dps/products/key-02.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.6,
  51,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-backpack'),
  'keyrings-backpack',
  'Mini Backpack Keychain',
  'Mini Backpack Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  149,
  229,
  NULL,
  35,
  '["/images/3dps/products/key-03.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.7,
  36,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-caduceus'),
  'keyrings-caduceus',
  'Caduceus Medical Keychain',
  'Caduceus Medical Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  179,
  279,
  NULL,
  36,
  '["/images/3dps/products/key-04.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.8,
  29,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-oreo'),
  'keyrings-oreo',
  'Oreo Cookie Keychain',
  'Oreo Cookie Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  129,
  199,
  NULL,
  35,
  '["/images/3dps/products/key-05.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.6,
  63,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-shiva'),
  'keyrings-shiva',
  'Mahadev Face Keychain',
  'Mahadev Face Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  149,
  229,
  NULL,
  35,
  '["/images/3dps/products/key-09.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.8,
  72,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-name'),
  'keyrings-name',
  'Custom Name Keychain',
  'Custom Name Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  199,
  299,
  NULL,
  33,
  '["/images/3dps/products/key-10.png"]'::jsonb,
  NULL,
  'new',
  false,
  4.9,
  88,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-numberplate'),
  'keyrings-numberplate',
  'Custom Number Plate Keychain',
  'Custom Number Plate Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  199,
  299,
  NULL,
  33,
  '["/images/3dps/products/pooja-06.png"]'::jsonb,
  NULL,
  'new',
  false,
  4.8,
  67,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-airplane'),
  'keyrings-airplane',
  'Paper Airplane Keychain',
  'Paper Airplane Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  129,
  199,
  NULL,
  35,
  '["/images/3dps/products/pooja-07.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.5,
  31,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-nike'),
  'keyrings-nike',
  'Slides Keychain',
  'Slides Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  149,
  229,
  NULL,
  35,
  '["/images/3dps/products/pooja-08.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.6,
  42,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-iphone'),
  'keyrings-iphone',
  'Mini Phone Keychain',
  'Mini Phone Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  179,
  269,
  NULL,
  33,
  '["/images/3dps/products/game-02.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.7,
  38,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-gymplate'),
  'keyrings-gymplate',
  'Custom Gym Weight Plate Keychain',
  'Custom Gym Weight Plate Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  199,
  299,
  NULL,
  33,
  '["/images/3dps/products/game-03.png"]'::jsonb,
  NULL,
  'new',
  false,
  4.8,
  55,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-puppy'),
  'keyrings-puppy',
  'Knitted Puppy Keychain',
  'Knitted Puppy Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  199,
  299,
  NULL,
  33,
  '["/images/3dps/products/decor-02.webp"]'::jsonb,
  NULL,
  'sale',
  false,
  4.9,
  74,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'keyrings-tennis'),
  'keyrings-tennis',
  'Tennis Ball Keychain',
  'Tennis Ball Keychain — personalised, multi-colour and built to last. Lightweight, durable, and perfect for keys or bag tags.',
  'keyrings',
  129,
  199,
  NULL,
  35,
  '["/images/3dps/products/decor-03.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.6,
  49,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'gaming-ak47'),
  'gaming-ak47',
  'AK-47 Keychain',
  'AK-47 Keychain — a fun, collectible 3D-printed piece for fans and gamers. Crisp detail and vibrant colour, made to order.',
  'gaming',
  179,
  279,
  NULL,
  36,
  '["/images/3dps/products/game-01.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.7,
  46,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'gaming-marlboro'),
  'gaming-marlboro',
  'Marlboro Keychain',
  'Marlboro Keychain — a fun, collectible 3D-printed piece for fans and gamers. Crisp detail and vibrant colour, made to order.',
  'gaming',
  149,
  229,
  NULL,
  35,
  '["/images/3dps/products/game-04.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.5,
  33,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'gaming-toad'),
  'gaming-toad',
  'Toad Character Keychain',
  'Toad Character Keychain — a fun, collectible 3D-printed piece for fans and gamers. Crisp detail and vibrant colour, made to order.',
  'gaming',
  199,
  299,
  NULL,
  33,
  '["/images/3dps/products/pooja-05.png"]'::jsonb,
  NULL,
  'new',
  false,
  4.8,
  41,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'gaming-shield'),
  'gaming-shield',
  'Captain America Shield Keychain',
  'Captain America Shield Keychain — a fun, collectible 3D-printed piece for fans and gamers. Crisp detail and vibrant colour, made to order.',
  'gaming',
  199,
  299,
  NULL,
  33,
  '["/images/3dps/products/decor-01.webp"]'::jsonb,
  NULL,
  'sale',
  false,
  4.9,
  69,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'gaming-streamer'),
  'gaming-streamer',
  'Gamer Character Keychain',
  'Gamer Character Keychain — a fun, collectible 3D-printed piece for fans and gamers. Crisp detail and vibrant colour, made to order.',
  'gaming',
  199,
  299,
  NULL,
  33,
  '["/images/3dps/products/decor-04.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.7,
  37,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'gaming-gamepad'),
  'gaming-gamepad',
  'Gamepad Keychain',
  'Gamepad Keychain — a fun, collectible 3D-printed piece for fans and gamers. Crisp detail and vibrant colour, made to order.',
  'gaming',
  179,
  269,
  NULL,
  33,
  '["/images/3dps/hero/slide-5.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.8,
  58,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id,
  slug,
  name,
  description,
  category,
  price,
  original_price,
  compare_price,
  discount_percentage,
  images,
  second_image_url,
  label_type,
  is_sold_out,
  rating,
  review_count,
  care_guide,
  shipping_info,
  stock_quantity,
  is_active
) VALUES (
  uuid_generate_v5('b6e0f8a2-1c3d-4e5f-8a9b-0c1d2e3f4a5b'::uuid, 'gaming-question'),
  'gaming-question',
  'Question Block Keychain',
  'Question Block Keychain — a fun, collectible 3D-printed piece for fans and gamers. Crisp detail and vibrant colour, made to order.',
  'gaming',
  149,
  229,
  NULL,
  35,
  '["/images/3dps/hero/slide-6.png"]'::jsonb,
  NULL,
  'sale',
  false,
  4.7,
  44,
  'Wipe gently with a soft, dry cloth. Avoid harsh chemicals and prolonged direct sunlight to keep colours vivid.',
  'Made to order and dispatched in 2–4 days. Free shipping on orders over ₹199. Tracked & insured pan-India delivery.',
  100,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  compare_price = EXCLUDED.compare_price,
  discount_percentage = EXCLUDED.discount_percentage,
  images = EXCLUDED.images,
  second_image_url = EXCLUDED.second_image_url,
  label_type = EXCLUDED.label_type,
  is_sold_out = EXCLUDED.is_sold_out,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  care_guide = EXCLUDED.care_guide,
  shipping_info = EXCLUDED.shipping_info,
  is_active = true,
  updated_at = NOW();


-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================
SELECT slug, id, name, category, price, label_type FROM products ORDER BY category, slug;
SELECT category, COUNT(*) AS count FROM products GROUP BY category ORDER BY category;
SELECT COUNT(*) AS total_products FROM products;
