import type { HomepageSettings } from './types'

export const DEFAULT_HOMEPAGE_SETTINGS: HomepageSettings = {
  sections: {
    hero: true,
    categories: true,
    promo: true,
    bestSellers: true,
    trust: true,
    rails: true,
    reviews: true,
    photoUpload: true,
    ideaCta: true,
    instagram: true,
    newsletter: true,
  },
  heroSlides: [
    {
      eyebrow: 'Personalized Home Decor',
      headline: 'Names,',
      highlight: 'printed as art.',
      subcopy:
        'Studio-shot name signs, photo gifts and shelf pieces — made to order in Agra and packed ready to gift.',
      ctaLabel: 'Shop Home Decor',
      ctaHref: '/products?category=home-decor',
      productIds: [
        'home-decor-alphabet-name',
        'home-decor-sliding-photo-book',
        'home-decor-instax-magnet',
        'home-decor-couple-initials',
        'home-decor-photo-rotator',
        'home-decor-butterfly-name',
        'home-decor-couple-name',
        'home-decor-mermaid-vase',
      ],
    },
    {
      eyebrow: 'Name Signs & Keepsakes',
      headline: 'Made for',
      highlight: 'your people.',
      subcopy:
        'Door nameplates, couple miniatures, first-year boards and bilingual signs — personalised after you order.',
      ctaLabel: 'See Name Gifts',
      ctaHref: '/products?category=home-decor',
      productIds: [
        'home-decor-kids-door-nameplate',
        'home-decor-couple-miniature',
        'home-decor-twisted-loop',
        'home-decor-child-car',
        'home-decor-first-year-board',
        'home-decor-sitar-plaque',
        'home-decor-umbrella-lady',
        'home-decor-bilingual-name',
      ],
    },
    {
      eyebrow: 'Desk & Workspace',
      headline: 'Organised,',
      highlight: 'and personal.',
      subcopy:
        'Named pen stands, giant pencils, jewellery dishes and wall key holders — colour and text customisable.',
      ctaLabel: 'Shop Workspace',
      ctaHref: '/products?category=organizers',
      productIds: [
        'organizers-desk-pen-holder',
        'organizers-giant-name-pencil',
        'organizers-name-pen-stand',
        'organizers-pencil-shape-stand',
        'organizers-wall-key-holder',
        'organizers-seashell-jewelry-dish',
        'organizers-bow-jewelry-basket',
        'organizers-name-perfume-tray',
      ],
    },
    {
      eyebrow: 'Pooja & Decor',
      headline: 'Devotion,',
      highlight: 'beautifully printed.',
      subcopy:
        'Intricately detailed idols, diya stands and pooja essentials crafted for your sacred space.',
      ctaLabel: 'Shop Pooja & Decor',
      ctaHref: '/products?category=pooja-decor',
      productIds: [
        'pooja-decor-kanhaji',
        'pooja-decor-aham-brahmasmi',
        'pooja-decor-ganesha',
        'pooja-decor-lakshmi',
        'pooja-decor-krishna',
        'pooja-decor-temple',
      ],
    },
    {
      eyebrow: 'Keyrings & Bag Tags',
      headline: 'Personalised,',
      highlight: 'built to last.',
      subcopy:
        'Name keyrings and bag tags printed in vivid multi-colour — the perfect little everyday statement.',
      ctaLabel: 'Shop Keyrings',
      ctaHref: '/products?category=keyrings',
      productIds: ['keyrings-name', 'keyrings-puppy', 'keyrings-tennis', 'keyrings-shiva'],
    },
    {
      eyebrow: 'Gaming & Fun',
      headline: 'One-of-a-kind,',
      highlight: 'made to order.',
      subcopy:
        'Collectible 3D-printed pieces for fans and gamers — crisp detail, bold colour, endless personality.',
      ctaLabel: 'Shop Gaming',
      ctaHref: '/products?category=gaming',
      productIds: ['gaming-shield', 'gaming-gamepad', 'gaming-toad', 'gaming-question'],
    },
  ],
  bestSellerIds: [
    'home-decor-alphabet-name',
    'organizers-desk-pen-holder',
    'pooja-decor-kanhaji',
    'home-decor-couple-initials',
    'organizers-giant-name-pencil',
    'home-decor-sliding-photo-book',
    'home-decor-butterfly-name',
    'organizers-name-pen-stand',
    'home-decor-couple-name',
    'organizers-wall-key-holder',
    'home-decor-photo-rotator',
    'home-decor-first-year-board',
    'organizers-pencil-shape-stand',
    'pooja-decor-aham-brahmasmi',
    'home-decor-couple-miniature',
    'organizers-name-perfume-tray',
    'home-decor-instax-magnet',
    'home-decor-mermaid-vase',
    'organizers-seashell-jewelry-dish',
    'home-decor-kids-door-nameplate',
    'organizers-bow-jewelry-basket',
    'home-decor-child-car',
    'home-decor-sitar-plaque',
    'home-decor-umbrella-lady',
    'organizers-office-name-sign',
    'home-decor-twisted-loop',
    'home-decor-bilingual-name',
  ],
  promo: {
    enabled: true,
    headline: '20% OFF your first order',
    subcopy: 'One-time use · Min order ₹199 · Free shipping on orders over ₹199',
    code: 'FIRST20',
  },
  categoryRails: [
    {
      slug: 'home-decor',
      title: 'Home Decor',
      subtitle: 'Personalised name signs, photo gifts and shelf pieces.',
    },
    {
      slug: 'organizers',
      title: 'Desk & Workspace',
      subtitle: 'Named pen stands, trays and wall organisers.',
    },
    {
      slug: 'pooja-decor',
      title: 'Pooja & Decor',
      subtitle: 'Devotional pieces, beautifully printed.',
    },
    {
      slug: 'keyrings',
      title: 'Keyrings & Bag Tags',
      subtitle: 'Personalised, multi-colour and built to last.',
    },
    {
      slug: 'gaming',
      title: 'Gaming & Fun',
      subtitle: 'One-of-a-kind, made-to-order creations.',
    },
    {
      slug: 'lamps',
      title: 'Lamps & Lighting',
      subtitle: 'Statement pieces that cast the perfect glow.',
    },
    {
      slug: 'planters',
      title: 'Planters & Garden',
      subtitle: 'Unique planters for succulents, herbs, and house plants.',
    },
  ],
}

export const HOMEPAGE_SECTION_LABELS: Record<keyof HomepageSettings['sections'], string> = {
  hero: 'Hero carousel',
  categories: 'Shop by category',
  promo: 'Promo strip',
  bestSellers: 'Best sellers',
  trust: 'Trust band',
  rails: 'Category product rails',
  reviews: 'Customer reviews',
  photoUpload: 'Photo upload / custom',
  ideaCta: 'Idea / custom CTA',
  instagram: 'Instagram reels',
  newsletter: 'Newsletter',
}
