/**
 * types.ts — Shared types for the Pinterest autopilot.
 *
 * Kept dependency-free (no SDK imports) so both the pure logic modules and the
 * Jest tests can import these without pulling in ESM-only packages.
 */

/**
 * The subset of a catalog product we actually use. `lib/products.json` has many
 * more fields (see app/products/[id]/page.tsx); we intentionally read only what
 * we need and tolerate the rest.
 */
export interface Product {
  id: string
  name: string
  description: string
  /** Relative image paths, e.g. "/images/products/lamps/lamp1/<uuid>.jpg". */
  images: string[]
  category: string
  price: number
  originalPrice?: number
}

/** SEO metadata generated by Claude, validated against the SEO contract. */
export interface SeoContent {
  /** Catchy hook + primary keyword. ≤100 chars (Pinterest title limit). */
  title: string
  /** Engaging copy with 3–4 natural related search terms. ≤500 chars, no hashtags. */
  description: string
  /** Broad board category, e.g. "3D Printed Pooja Decor". */
  board_suggestion: string
}

/** One recorded successful post — the unit stored in posted-log.json. */
export interface PostRecord {
  productId: string
  pinId: string
  boardId: string
  boardName: string
  title: string
  link: string
  /** ISO-8601 timestamp of when the post was recorded. */
  postedAt: string
}

/** The committed de-dupe + rotation store. */
export interface PostedLog {
  version: 1
  posts: PostRecord[]
}

/** A board as returned by GET /v5/boards. */
export interface Board {
  id: string
  name: string
}

/** The response we care about from POST /v5/pins. */
export interface CreatedPin {
  id: string
}
